import { Routes,Route,Link,useParams,useNavigate,useLocation } from 'react-router-dom'
import { ArrowRight, ChevronRight, Heart, Minus, Plus, ShoppingBag, SlidersHorizontal, Star, Truck, RotateCcw, ShieldCheck, X } from 'lucide-react'
import { motion,AnimatePresence } from 'framer-motion'
import { Header } from './components/Header'
import { Footer } from './components/Footer'
import { ProductCard } from './components/ProductCard'
import { products,featured } from './data/products'
import { useStore } from './store/useStore'
import { AdminPanel } from './components/AdminPanel'

const catImages=['photo-1551698618-1dfe5d97d256','photo-1517836357463-d25dfeac3438','photo-1579952363873-27d3bfad9c0d','photo-1519861531473-9200262188bf','photo-1521572163474-6864f9cf17ab']
function Home(){return <><section className="hero"><img src="https://images.unsplash.com/photo-1517838277536-f5f99be501b2?auto=format&fit=crop&w=2000&q=90"/><div className="hero-overlay"/><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.15}}><p>SPRING / SUMMER 24</p><h1>MOVE<br/><em>YOUR WAY.</em></h1><div><Link to="/shop/men" className="btn white">Shop men <ArrowRight/></Link><Link to="/shop/women" className="btn outline">Shop women <ArrowRight/></Link></div></motion.div><span className="hero-index">01 / 04</span></section><section className="intro section"><p className="eyebrow">BUILT FOR EVERY DAY</p><h2>Performance lives<br/>outside the lines.</h2><Link to="/shop/new" className="text-link">Discover our story <ArrowRight/></Link></section><section className="section"><div className="section-head"><h2>Shop by sport</h2><Link to="/shop/all">View all <ArrowRight/></Link></div><div className="category-grid">{['Running','Training','Football','Basketball','Lifestyle'].map((x,i)=><Link to={`/shop/${x.toLowerCase()}`} className="category" key={x}><img src={`https://images.unsplash.com/${catImages[i]}?auto=format&fit=crop&w=700&q=85`}/><div><h3>{x}</h3><span>Shop now <ArrowRight/></span></div></Link>)}</div></section><section className="section featured"><div className="section-head"><div><p className="eyebrow">JUST DROPPED</p><h2>New in motion</h2></div><Link to="/shop/new">Shop all <ArrowRight/></Link></div><div className="product-grid">{featured.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><section className="campaign"><img src="https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1800&q=90"/><div><p>RUNNING / 2024</p><h2>Leave<br/>the noise.</h2><Link className="btn white" to="/shop/running">Explore running <ArrowRight/></Link></div></section><section className="section split"><div className="split-img"><img src="https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=85"/></div><div className="split-copy"><p className="eyebrow">THE STUDIO COLLECTION</p><h2>Set your<br/><em>own pace.</em></h2><p>Essential shapes. Precise details. Pieces that are ready for every version of your day.</p><Link to="/shop/clothing" className="text-link">Shop the collection <ArrowRight/></Link></div></section><section className="newsletter"><p className="eyebrow">STAY IN THE LOOP</p><h2>A little more<br/>movement in your inbox.</h2><div className="newsletter-input"><input placeholder="Enter your email address"/><button><ArrowRight/></button></div></section></>}
function Listing(){const {slug}=useParams();const title=slug==='sale'?'Sale':slug?slug.replace(/^./,c=>c.toUpperCase()):'Shop all';const list=slug==='sale'?products.filter(p=>p.originalPrice):products;return <main className="listing section"><div className="crumb">Home <ChevronRight/> {title}</div><div className="listing-heading"><h1>{title}</h1><p>{list.length} products</p></div><div className="catalog-bar"><button><SlidersHorizontal/> Filters</button><span>Sort by <b>Featured</b></span></div><div className="catalog"><aside><b>FILTER BY</b>{['Gender','Category','Size','Colour','Price','Discount'].map(x=><details key={x}><summary>{x}<Plus size={15}/></summary><label><input type="checkbox"/> New arrivals</label><label><input type="checkbox"/> Best sellers</label></details>)}</aside><div className="product-grid">{list.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></main>}
function ProductDetail(){const {id}=useParams();const product=products.find(x=>x.id===id)||products[0];const {addToCart,wishlist,toggleWish}=useStore();return <main className="product-page section"><div className="crumb">Home <ChevronRight/> {product.category} <ChevronRight/> {product.name}</div><div className="product-layout"><div className="gallery"><img src={product.image}/><img src={product.image2}/></div><div className="product-info"><p className="eyebrow">{product.category} · {product.gender}</p><h1>{product.name}</h1><div className="rating"><Star size={15} fill="currentColor"/> {product.rating.toFixed(1)} <u>{product.reviews} reviews</u></div><div className="detail-price">${product.price} {product.originalPrice&&<del>${product.originalPrice}</del>}</div><hr/><p className="label">COLOUR: <b>ONYX BLACK</b></p><div className="swatches large">{product.colors.map(c=><i key={c} style={{background:c}}/>)}</div><p className="label">SELECT SIZE <u>Size guide</u></p><div className="sizes">{product.sizes.map(s=><button key={s}>{s}</button>)}</div><button className="add" onClick={()=>addToCart(product)}>Add to bag <ShoppingBag size={18}/></button><button className="wish-big" onClick={()=>toggleWish(product.id)}><Heart fill={wishlist.includes(product.id)?'currentColor':'none'}/> Add to wishlist</button><div className="perks"><span><Truck/> Free shipping over $125</span><span><RotateCcw/> Easy 30-day returns</span><span><ShieldCheck/> 2-year quality promise</span></div><details open><summary>Description <Plus size={16}/></summary><p>{product.description}</p></details><details><summary>Details & materials <Plus size={16}/></summary></details></div></div><section className="related"><div className="section-head"><h2>You may also like</h2></div><div className="product-grid">{featured.slice(2,6).map(p=><ProductCard key={p.id} product={p}/>)}</div></section></main>}
function Cart(){const {cart,removeFromCart}=useStore();const sum=cart.reduce((n,x)=>n+x.product.price*x.quantity,0);return <main className="section cart-page"><h1>Your bag <small>({cart.length})</small></h1>{!cart.length?<div className="empty"><ShoppingBag/><h2>Your bag is empty</h2><Link className="btn dark" to="/shop/all">Continue shopping</Link></div>:<div className="cart-layout"><div>{cart.map(x=><article className="cart-item" key={x.product.id}><img src={x.product.image}/><div><p>{x.product.category}</p><h3>{x.product.name}</h3><span>Size {x.size} · Black</span><b>${x.product.price}</b><button onClick={()=>removeFromCart(x.product.id)}><X size={16}/> Remove</button></div><div className="qty"><Minus size={14}/>{x.quantity}<Plus size={14}/></div></article>)}</div><aside className="summary"><h3>Order summary</h3><div><span>Subtotal</span><b>${sum}</b></div><div><span>Shipping</span><b>Free</b></div><hr/><div className="total"><span>Total</span><b>${sum}</b></div><Link className="btn dark full" to="/checkout">Checkout <ArrowRight/></Link><p>Taxes calculated at checkout.</p></aside></div>}</main>}
function Wishlist(){const {wishlist}=useStore();const saved=products.filter(p=>wishlist.includes(p.id));return <main className="section listing"><div className="listing-heading"><h1>Wishlist</h1><p>{saved.length} saved pieces</p></div>{saved.length?<div className="product-grid">{saved.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty"><Heart/><h2>Nothing saved yet</h2><Link className="btn dark" to="/shop/all">Explore products</Link></div>}</main>}
function Checkout(){const nav=useNavigate();return <main className="checkout section"><div><p className="eyebrow">SECURE CHECKOUT</p><h1>Almost there.</h1><div className="checkout-card"><h3>Contact information</h3><input placeholder="Email address"/><h3>Delivery address</h3><div className="two"><input placeholder="First name"/><input placeholder="Last name"/></div><input placeholder="Address"/><div className="two"><input placeholder="City"/><input placeholder="Postal code"/></div><h3>Payment method</h3><button className="payment">Credit / debit card <span>VISA · MC</span></button><button className="btn dark full" onClick={()=>nav('/order-confirmed')}>Place order <ArrowRight/></button></div></div><aside className="summary"><h3>Your order</h3><p>Items and totals will be confirmed on the next step.</p><div className="total"><span>Estimated total</span><b>$110</b></div></aside></main>}
function Confirmation(){return <main className="empty confirm"><ShieldCheck/><p className="eyebrow">ORDER CONFIRMED</p><h1>You're in motion.</h1><p>Thanks for your order. We’ll send a shipping confirmation shortly.</p><Link to="/shop/all" className="btn dark">Keep shopping <ArrowRight/></Link></main>}
function SearchPage(){const loc=useLocation();const q=new URLSearchParams(loc.search).get('q')||'';const results=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase()));return <main className="section listing"><p className="eyebrow">SEARCH THE COLLECTION</p><form className="search-form"><input defaultValue={q} name="q" placeholder="Search products"/><button><SearchIcon/></button></form><div className="listing-heading"><h1>{q?`Results for “${q}”`:'Find your next move'}</h1><p>{q?results.length:'30'} products</p></div>{results.length?<div className="product-grid">{results.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty"><h2>No pieces found</h2><p>Try “running”, “training”, or “classic”.</p></div>}</main>}
function SearchIcon(){return <span>→</span>}
function Account(){return <main className="section account"><div><p className="eyebrow">MY AERØ</p><h1>Welcome back,<br/><em>Alex.</em></h1><p className="account-lead">Manage your profile, orders and saved pieces from one place.</p></div><div className="account-grid"><Link to="/orders"><b>Orders</b><span>View your order history <ArrowRight/></span></Link><Link to="/wishlist"><b>Wishlist</b><span>Saved for later <ArrowRight/></span></Link><a><b>Profile & preferences</b><span>Update your details <ArrowRight/></span></a><a><b>Addresses</b><span>Manage saved addresses <ArrowRight/></span></a></div></main>}
function Auth({register=false}:{register?:boolean}){const nav=useNavigate();return <main className="auth"><section><p className="eyebrow">MY AERØ</p><h1>{register?'Create your account':'Welcome back.'}</h1><p>{register?'Join our movement and get early access to new drops.':'Sign in to access your orders, saved pieces and more.'}</p><form onSubmit={e=>{e.preventDefault();nav('/account')}}>{register&&<input placeholder="Full name"/>}<input type="email" placeholder="Email address"/><input type="password" placeholder="Password"/><button className="btn dark full">{register?'Create account':'Sign in'} <ArrowRight/></button></form><small>{register?'Already part of AERØ?':'New to AERØ?'} <Link to={register?'/login':'/register'}>{register?'Sign in':'Create an account'}</Link></small></section><div className="auth-image"/></main>}
function Orders(){return <main className="section orders"><p className="eyebrow">MY AERØ / ORDERS</p><h1>Order history</h1><article className="order-row"><img src={products[0].image}/><div><p>ORDER #AERO-24105</p><h3>Delivered · May 18, 2024</h3><span>Velocity NXT · 1 item</span></div><b>$85.00</b><Link className="text-link" to="/orders/AERO-24105">View order <ArrowRight/></Link></article></main>}
function NotFound(){return <main className="empty not-found"><p className="eyebrow">ERROR 404</p><h1>Wrong turn.</h1><p>The page you’re looking for moved on.</p><Link className="btn dark" to="/">Back home <ArrowRight/></Link></main>}
function Shell({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}; function App(){return <Routes><Route path="/admin" element={<AdminPanel/>}/><Route path="*" element={<Shell><Routes><Route path="/" element={<Home/>}/><Route path="/shop/:slug" element={<Listing/>}/><Route path="/sale" element={<Listing/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/product/:id" element={<ProductDetail/>}/><Route path="/cart" element={<Cart/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/order-confirmed" element={<Confirmation/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/account" element={<Account/>}/><Route path="/orders" element={<Orders/>}/><Route path="/orders/:id" element={<Orders/>}/><Route path="*" element={<NotFound/>}/></Routes></Shell>}/></Routes>};export default App
